### ISSUE TITLE
search value should be at the search field

### ISSUE THREAD

**Issue by ArindamBiswas-dev** [ShivamKun/Sakamoto#106]
**Describe the bug**
When we search for an item, the search input field does not keep the search text.

**To Reproduce**
1. Go to the Home page
2. Click on the Search input field
3. Search anything
4. See the search input field does not keep the text that you have inputted

**Expected behavior**
The search input field should keep the text that you have inputted.

**Screenshots**
![Screenshot from 2022-10-16 08-32-07](https://user-images.githubusercontent.com/69881224/196015966-50de5376-9dc2-48cc-8fec-5d965e490dd3.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Brave
 - Version: 1.43.93

**Comment by mnosov622** [comment]
Hi !

I would love to work on this issue.

Could you assign it to me, please?

**Comment by ShivamKun** [comment]
well it works fine on safari, edge and chrome
