### ISSUE TITLE
PWA support

### ISSUE THREAD

**Issue by rak3n** [ShivamKun/Sakamoto#109]
**Is your feature request related to a problem? Please describe.**
Make the platform accessible faster, and quickly available to be used by the user on there device.

**Describe the solution you'd like**
Add support for Progressive Web App making users install the platform as an App on their devices. This will also enable the possibility to bring notification-related features in a later stage too.

**Describe alternatives you've considered**
This will require registering a service worker with the App.

**Additional context**
![Screenshot (150)](https://user-images.githubusercontent.com/39650482/196166705-963552ba-dffb-4046-b761-d8729d59a826.png)

**Comment by ShivamKun** [comment]
yeah would be cool with webmanifest...
