### ISSUE TITLE
Add anime manually ?

### ISSUE THREAD

**Issue by souzx17** [ShivamKun/Sakamoto#114]
Do you have a wordpress theme or something like that? I wanted to use it to add anime from my region, it's very well optimized.

**Comment by ShivamKun** [comment]
i think it would be a mess tho...

**Comment by souzx17** [comment]
> 

Seriously ? why ?

**Comment by ShivamKun** [comment]
Like what anime would u add manually?
This website doesnt have a database of its own. Its just scraper that fetches anime from pirated websites and display them without ads.
