### ISSUE TITLE
Dockerize the application 

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [ShivamKun/Sakamoto#117]
I can containerize this application with Docker. This will make it more scalable.

**Comment by ShivamKun** [comment]
yeah sure...

**Comment by pruthvirajjadhav1** [comment]
Do you how to solve this
![Screenshot (89)](https://user-images.githubusercontent.com/73253354/200842879-115df69b-cd23-4202-b9ba-67dd5eab7a68.png)

**Comment by ShivamKun** [comment]
maybe some alters in `package.json` and `package-lock.json`
