### ISSUE TITLE
Can you add a server changer and dub changer style like 9anime.

### ISSUE THREAD

**Issue by Wava123** [ShivamKun/Sakamoto#118]
Can you add a server changer and dub style like 9anime.
![image](https://user-images.githubusercontent.com/117023322/198882335-18d952c0-9ff3-4fc3-ba4b-6a9655460ce5.png)

**Comment by ShivamKun** [comment]
The server changer thing is already there...
About that dub style thing, we can't. This website simply scraps anime from other websites already with subs in the video... so its not possible for now.
![Screenshot_2022-10-30-19-28-38-26_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91766105/198882627-4c463ed9-0061-4f0e-b12c-2baffa7f01c2.jpg)
