### ISSUE TITLE
Deployed site shows blank skeletons with no content 

### ISSUE THREAD

**Issue by Lauriex** [ShivamKun/Sakamoto#16]
Hell there!
First of all your project is amazing and beautiful. I tried installing the site but it only shows blank skeletons. Am I missing a step? Thanks.

**Comment by ShivamKun** [comment]
Ah no you are not missing any steps... that's just because it uses a custom API too [sakamoto-api.vercel.app](https://sakamoto-api.vercel.app).
If you want, I can add you deployment in the backend repo that will show the anime content... but cant change its visibility right now. 
Hope you understand and thank you for checking out this repo ❤️

**Comment by Lauriex** [comment]
That would be amazing!.  The love of anime brought me here and I'm thankful I found your repository. Because of you, I'm going to start learning about react!

**Comment by ShivamKun** [comment]
Alright just drop your frontend web url here... I'll add it to the backend repo

**Comment by Jeydin** [comment]
Wait, why not just fork the backend repository?

**Comment by Lauriex** [comment]
> Alright just drop your frontend web url here... I'll add it to the backend repo

Thanks! [Frontend](https://sugoidekai.xyz/)

Do you take Paypal?

**Comment by ShivamKun** [comment]
> > Alright just drop your frontend web url here... I'll add it to the backend repo
> 
> Thanks! [Frontend](https://sugoidekai.xyz/)
> 
> Do you take Paypal?

nah... even the whole work is'nt mine

**Comment by ShivamKun** [comment]
> Wait, why not just fork the backend repository?

cuz its not based on that initial api... makin things faster with no rate limits...

**Comment by Lauriex** [comment]
> > > Alright just drop your frontend web url here... I'll add it to the backend repo
> > 
> > 
> > Thanks! [Frontend](https://sugoidekai.xyz/)
> > Do you take Paypal?
> 
> nah... even the whole work is'nt mine. gonna add that tomorrow...

Thanks!

**Comment by Lauriex** [comment]
> > Wait, why not just fork the backend repository?
> 
> cuz its not based on that initial api... makin things faster with no rate limits...

I'm sorry to say this, but this realm of GitHub is quite new to me but hopefully I'll get a hang of it to fork repositories and do a lot more.

**Comment by ShivamKun** [comment]
Put dis [link](https://lauriex.vercel.app) in ur .env file

**Comment by ShivamKun** [comment]
@Lauriex didya try dat?

**Comment by Lauriex** [comment]
> @Lauriex didya try dat?

Hi there, finally got some content to show but as soon as I click on the anime it displays skeletons. I had some errors during the compilation in vscode https://prnt.sc/HSRaOdCxn-ab And I'm someone who has never touched react before so I guess there are a few things I have missed or not included. It's still a great project though. A bit tricky for noobs haha.

**Comment by ShivamKun** [comment]
waw
