### ISSUE TITLE
I need help

### ISSUE THREAD

**Issue by 0vql** [ShivamKun/Sakamoto#19]
Hello why i run the app to i only see the skeleton no image i need help u think it's cause of the .env or smt

**Comment by ShivamKun** [comment]
> Hello why i run the app to i only see the skeleton no image i need help u think it's cause of the .env or smt

cuz it uses an api too... if you want... i can add your frontend to that api.

**Comment by ShivamKun** [comment]
but just if u wanna learn reactjs

**Comment by 0vql** [comment]
> > Hello why i run the app to i only see the skeleton no image i need help u think it's cause of the .env or smt
> 
> cuz it uses an api too... if you want... i can add your frontend to that api.

Yeah can I get a api please

**Comment by 0vql** [comment]
> but just if u wanna learn reactjs. I mean not fo commercial use uk 🥲 (well who's gonna stop you)

Um...... I accidentally clicked Europe.

**Comment by 0vql** [comment]
> but just if u wanna learn reactjs. I mean not fo commercial use uk 🥲 (well who's gonna stop you)

Um...... I accidentally clicked Europe.

**Comment by 0vql** [comment]
And here's the front-end https://izlu.vercel.app/

**Comment by 0vql** [comment]
> but just if u wanna learn reactjs. I mean not fo commercial use uk 🥲 (well who's gonna stop you)

Nah I am only learning python

**Comment by 0vql** [comment]
Thanks man

**Comment by 0vql** [comment]
Still loading still skeleton

**Comment by ShivamKun** [comment]
> Still loading still skeleton

![image](https://user-images.githubusercontent.com/91766105/187836758-2490d2a2-afeb-45fc-bcda-9e598455eaa9.png)
Umm can u show me the deployment

**Comment by ShivamKun** [comment]
@0vql looks like you haven't promoted the deployment to production. Just a wild guess<img src="https://media3.giphy.com/media/eSwGh3YK54JKU/giphy.gif"/>

**Comment by 0vql** [comment]
> @0vql looks like you haven't promoted the deployment to production. Just a wild guess![](https://camo.githubusercontent.com/6ff31f5f696ee19be35985a0da4d97ed2120e679cedf881682c1177dea5828ed/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f655377476833594b35344a4b552f67697068792e676966) [ ![68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f655377476833594b35344a4b552f67697068792e676966](https://camo.githubusercontent.com/6ff31f5f696ee19be35985a0da4d97ed2120e679cedf881682c1177dea5828ed/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f655377476833594b35344a4b552f67697068792e676966) ](https://camo.githubusercontent.com/6ff31f5f696ee19be35985a0da4d97ed2120e679cedf881682c1177dea5828ed/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f655377476833594b35344a4b552f67697068792e676966) [ ](https://camo.githubusercontent.com/6ff31f5f696ee19be35985a0da4d97ed2120e679cedf881682c1177dea5828ed/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f655377476833594b35344a4b552f67697068792e676966)

I think I did tha

**Comment by 0vql** [comment]
Also like https://sakamoto-ten.vercel.app/ the link title changed

**Comment by ShivamKun** [comment]
> Also like https://sakamoto-ten.vercel.app/ the link title changed

You need to connect the backend to the frontend you sent - https://izlu.vercel.app
so basically you need to manage stuff like the production domain.

![image](https://user-images.githubusercontent.com/91766105/188030879-c803aa61-3357-483f-ad7c-b5bc90a884d1.png)
