### ISSUE TITLE
https://docs.sakamoto.live/ isn't working. Update the working url.

### ISSUE THREAD

**Issue by sainathd07** [ShivamKun/Sakamoto#35]
![image](https://user-images.githubusercontent.com/67309212/192448393-84985251-c131-4fde-8c08-8cc0faca370c.png)

The Docs link (https://docs.sakamoto.live/) isn't working. Update the working URL.

**Comment by ShivamKun** [comment]
I haven't added the subdomain yet. I guess I'll update that link soon. 
Temporarily, I have hosted the docs [here](https://shivamkun.github.io/Sakamoto).

**Comment by BrownGrey** [comment]
Docs...

**Comment by ShivamKun** [comment]
Done
