### ISSUE TITLE
Add a hover effect (text color change or button shadow appearance )on buttons in header on the site.

### ISSUE THREAD

**Issue by sainathd07** [ShivamKun/Sakamoto#36]
![image](https://user-images.githubusercontent.com/67309212/192448933-8cc7492a-f668-46e6-a0ad-007f88304508.png)

When we hover on the buttons on the site, there is no hover effect. A text color change looks good when we hover on the buttons.

**Comment by ShivamKun** [comment]
Umm, why not if it looks good... I will add it.

**Comment by Ujjawal3** [comment]
Hi @ShivamKun can i work on this as part of hacktoberfest contribution?

**Comment by ShivamKun** [comment]
> Hi @ShivamKun can i work on this as part of hacktoberfest contribution?

Ofcourse you can... The event starts on the first of October...

**Comment by ShivamKun** [comment]
Fixed
