### ISSUE TITLE
play and pause icon isn't visible on the player!

### ISSUE THREAD

**Issue by sainathd07** [ShivamKun/Sakamoto#37]
![image](https://user-images.githubusercontent.com/67309212/192684682-f3539aad-e5a0-430f-8390-c6e113112e8d.png)

The play and pause icon isn't visible on the player! Is it due to dark mode or its a bug by default?..look into it

**Comment by ShivamKun** [comment]
Some css probs i guess. I'll fix it.

**Comment by codewithshariq** [comment]
@ShivamKun I would like to work on this issue.
