### ISSUE TITLE
The text on the buttons on the player page isn't visible!

### ISSUE THREAD

**Issue by sainathd07** [ShivamKun/Sakamoto#38]
![image](https://user-images.githubusercontent.com/67309212/192684920-4d6fd452-4101-4285-82fa-79be90a389da.png)

The text on the player page on the buttons isn't visible. The text on the buttons on the general page looks fine..when we open a certain episode to watch..the recommended episodes button down of that seems to have the problem..

**Comment by ShivamKun** [comment]
Same as the other... Some css probs

**Comment by codewithshariq** [comment]
@ShivamKun I would like to work on this issue. I will send the PR once Hacktoberfest is started.

**Comment by ShivamKun** [comment]
ohok lol... leaving that one for you...

**Comment by codewithshariq** [comment]
> ohok lol... leaving that one for you...

Thank you.
