### ISSUE TITLE
Font size of the footer section should be bigger and more visible

### ISSUE THREAD

**Issue by sceary-expert** [ShivamKun/Sakamoto#40]
## This is the footer section which is not perfectly visible for devices of various dimensions

![image](https://user-images.githubusercontent.com/84634405/192787504-4da00cac-0270-4270-88d3-bb64b7fe9362.png)

 ## What if it looks like this? Don't you think it would be more visible then?

![image](https://user-images.githubusercontent.com/84634405/192787924-ba95f0de-f018-45bb-a3bb-1ec288634103.png)

### If you tell me where the file is located for the footer section then that will help to resolve this.

**Comment by ShivamKun** [comment]
I dont think so. Here is the footer reference:
![Footer](https://user-images.githubusercontent.com/91766105/192797666-47aac52e-9dfd-4509-b704-bac08fc9ba9a.jpg)
