### ISSUE TITLE
`UI` needs to be fixed

### ISSUE THREAD

**Issue by ShivamKun** [ShivamKun/Sakamoto#47]
### Current Production:
![{BF02AEB8-58E1-403C-B7E6-5F3FD89FF718}](https://user-images.githubusercontent.com/91766105/193379933-ae3a6e59-e523-45d7-abd4-4b23457ab62b.png)

### What we want:
![{8DF37D4C-46DE-43F0-ADAB-84734D292105}](https://user-images.githubusercontent.com/91766105/193379936-f3e1c1d3-c82e-4ea3-89fd-ca30f9561058.png)

**PS:** That `Internal Player` text on the top of the player is already there. Just with the same colour as its background.

### Rough Workflow:
- Remove button borders
- Button colour: #FFFFFF
- Text colour: #FFFFFF
- Video Player top: RGB(16, 16, 16)

**Comment by shikhr** [comment]
Hey, I looked into your codebase yesterday.  Can I work on this?

**Comment by ShivamKun** [comment]
> Hey @ShivamKun, I looked into your codebase yesterday. Can I work on this?

Yesss
