### ISSUE TITLE
Remove "Continue Watching" section when empty

### ISSUE THREAD

**Issue by codewithshariq** [ShivamKun/Sakamoto#50]
### Issue
The continue watching section on the homepage remains visible when it is empty.

### Suggested Improvement
I suggest the "Continue Watching" section should only be displayed when there is something to continue.

### Snapshot
Adding this snapshot for your reference

<img width="1365" alt="Screenshot 2022-10-01 at 3 00 44 PM" src="https://user-images.githubusercontent.com/67257981/193404012-f3a35125-789f-4a01-842b-3f2ddd0e80d7.png">

I would like to work on this issue.

**Comment by ShivamKun** [comment]
All the best!
