### ISSUE TITLE
Add a drop-down menu to filter episodes list

### ISSUE THREAD

**Issue by shikhr** [ShivamKun/Sakamoto#54]
It's frustrating to scroll down all the way to find the episode on an anime with a huge number of episodes. 

All anime sites have implemented paginated lists to solve this problem.

I have prototyped a drop-down based filter across a range(eg: 100 episodes). 

![1](https://user-images.githubusercontent.com/73433516/193415572-38ff9d37-aec8-4618-b5dc-db8f82e899c6.png)

![2](https://user-images.githubusercontent.com/73433516/193415573-15e7248a-f535-4dd0-8264-1bf9fbd36c61.png)

If you give me the go-ahead, I will:

- [x] Add functioning episode segregation and filter feature.
- [x] Create a custom drop-down menu component for UI consistency.
- [ ] Add functionality to set the episode range automatically based on the localStorage episode number(if stored).

I am waiting for your approval, @ShivamKun.

**Comment by ShivamKun** [comment]
That's cool, everything is fine until its minimalistic...
Approved :)
