### ISSUE TITLE
Inconsistent episode link styling

### ISSUE THREAD

**Issue by chris--jones** [ShivamKun/Sakamoto#60]
**Describe the bug**
There is a difference between the category episode links and the watch page including hover effects.
I feel this looks unintentional, but if it is intentional perhaps at least the text colour could be changed to increase contrast on the category page for accessibility reasons.

**To Reproduce**
1. Visit any category page such as through the via search results (e.g https://sakamoto.live/category/one-piece-dub)
2. Observe the episode buttons including states such as hover
3. Click an episode link to visit the watch page
4. Compare the episode links on the watch page (e.g. https://sakamoto.live/watch/one-piece-dub-episode-1)

**Expected behavior**
Expected consistent look and feel for all episode buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/10459377/193454675-48b61e48-9977-4645-afdd-9fdb0d1de3c5.png)
![image](https://user-images.githubusercontent.com/10459377/193454660-b0e8b0f4-f3df-4f53-8231-40fcc729f63a.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: This issue is not OS specific, but Linux
 - Browser [e.g. chrome, safari]: firefox
 - Version [e.g. 22]: 105.0.1

**Comment by ShivamKun** [comment]
lol i was about to create this issue

**Comment by ShivamKun** [comment]
Same with all OS ig...

**Comment by shikhr** [comment]
I am working on adding episode filters to the watch page in #54. In the end, I'm planning to extract the styles as reusable components, and use the same ones along with the filter on the category page as well. If it works out, it will solve this issue as well.

**Comment by ShivamKun** [comment]
oh

**Comment by ShivamKun** [comment]
then whom should i assign this issue?

**Comment by shikhr** [comment]
Since I am already working on the episode list on watch page, I will close both issues with the same PR later tonight or tomorrow. In the very unlikely case that I fail to make it work, I will let you know and someone else can work on this separately. Until then, there's no point in anyone else working on it from scratch. So, you can assign it to me.

**Comment by ShivamKun** [comment]
ohokk
