### ISSUE TITLE
Footer does not stay at bottom of the page when page content is not there

### ISSUE THREAD

**Issue by ArindamBiswas-dev** [ShivamKun/Sakamoto#61]
**Describe the bug**
The footer section does not stay at bottom of the page when page content is not there.

**To Reproduce**
1. Click on the search button
2. Search for something random (e.g https://sakamoto.live/search/random)

**Expected behavior**
The footer section should always be at bottom of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/69881224/193456203-81ba1b62-270d-4369-8447-7a77bf8ba2b5.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Brave
 - Version: 1.43.93

**Comment by ArindamBiswas-dev** [comment]
can you assign me this?

**Comment by ShivamKun** [comment]
here you go
