### ISSUE TITLE
Dynamic Page Titles

### ISSUE THREAD

**Issue by ShivamKun** [ShivamKun/Sakamoto#64]
Making the titles dynamic
```js
async function getAnimeDetails() {
    setLoading(true);
    setExpanded(false);
    window.scrollTo(0, 0);
    let res = await axios.get(
      `https://sakamoto-api.vercel.app/api/getanime?link=/category/${slug}`
    );
    setLoading(false);
    setAnimeDetails(res.data);
    getLocalStorage(res.data);
    document.title = animeDetails[0].gogoResponse.title
  }
```

**Comment by chris--jones** [comment]
I deliberately removed the document.title line from a duplicated function as part of my cleanup - setting the title in this way will keep it set unless you reset it on other pages, but this could quickly become unruly (you'd lose track of which pages are setting title and when).
A better approach might be to use a hook or global state to centralise the setting and make it easier for pages to set title in a consistent way. Then you could adjust things like the title prefix in one place.

**Comment by ShivamKun** [comment]
yemss

**Comment by Ilikepizza2** [comment]
Hello!
I'd like to work on this issues.
Can I be assigned?

**Comment by Ilikepizza2** [comment]
@chris--jones  I guess just using react-helmet would be a much better option to do this instead of creating a context?
What are your thoughts about this? : thinking :

**Comment by Ilikepizza2** [comment]
Gentle reminder

> @chris--jones I guess just using react-helmet would be a much better option to do this instead of creating a context? What are your thoughts about this? : thinking :

**Comment by chris--jones** [comment]
@Ilikepizza2 react-helmet is fine, but we also have this somewhat similar issue: https://github.com/ShivamKun/Sakamoto/issues/79
so it might make sense to bundle a bunch of these document tags into the same approach, essentially when you load a particular anime's details you're feeding all that info to one method that sets title, meta tags and any other context on the page.

**Comment by Ilikepizza2** [comment]
Makes sense : thinking : 
Alright I'll do it 👍
