### ISSUE TITLE
Regarding discrepancy in deployment

### ISSUE THREAD

**Issue by shikhr** [ShivamKun/Sakamoto#68]
@ShivamKun It would seem that the changes made by this latest bugfix commit #65 are not live yet on https://sakamoto.live.

localhost server: 

![image](https://user-images.githubusercontent.com/73433516/193500957-4395b50a-b282-446a-b347-784a81a99930.png)

https://sakamoto.live:

![image](https://user-images.githubusercontent.com/73433516/193500987-14f1312a-9127-4cce-9901-d74eded99897.png)

Is the commit not deployed yet, or is the fix not working on the deployment? Please let me know.

**Comment by ShivamKun** [comment]
oh looks like i forgot to deploy the commit to production

**Comment by ShivamKun** [comment]
lemme see

**Comment by ShivamKun** [comment]
deployed to production... Its working now
