### ISSUE TITLE
`Continue watching` Section

### ISSUE THREAD

**Issue by ShivamKun** [ShivamKun/Sakamoto#75]
the thing about adding confirmation to removing an anime from watch list is that the continue watching header still stays there after you remove the last anime in the list.

Got this issue from a member at the discord server.

**Comment by KaylaKremer** [comment]
Hello! I went ahead and fixed this in PR #76

**Comment by chris--jones** [comment]
Sorry, that was my fault - I didn't test that scenario.

Thanks for the fix @KaylaKremer  - I'll check it out now.

**Comment by chris--jones** [comment]
This fixes the "Continue Watching" message, but at the cost of causing Home to re-render upon each click to remove and confirm or cancel. Since this is not noticeable to users I guess it is better, but it bothers me.
