### ISSUE TITLE
Video Player Has No Quality Options

### ISSUE THREAD

**Issue by ShivamKun** [ShivamKun/Sakamoto#84]
The video player settings button is not working properly...

**Comment by ShivamKun** [comment]
![Screenshot_2022-10-06-09-38-33-95_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/91766105/194217738-47454933-59ce-406b-9969-d92c827a9384.jpg)

**Comment by KaylaKremer** [comment]
I definitely caused this bug with my refactoring, apologies. It looks like I targeted the wrong element and replaced the entire content with the Auto text. I'll have a PR up soon to fix this!

**Comment by ShivamKun** [comment]
@KaylaKremer Still not working...

**Comment by KaylaKremer** [comment]
Hello again! Sorry for the delayed reply and that my previous PR did not fix the issue. Looks like I only added back the speed options and not the quality options to the video player settings button. I just put up PR #96 to add the quality options back. If it still does not work for you, please let me know. Thanks!

**Comment by ShivamKun** [comment]
FIXED!!!
YAAAYY!!!
ARIGATO GOZAIMASU...
